project:
  default-view: redirect:/swagger-ui.html #swagger访问url:localhost:8081/swagger-ui.html

# 配置端口号
server:
  port: 8082

# 配置MySQL
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/newsblog?userSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

  # 整合Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:

# 整合mybatis
mybatis:
  type-aliases-package: com.hzy.pojo
  mapper-locations: classpath:mapper/*.xml

# 配置分页插件方言
pagehelper:
  helper-dialect: mysql

# 整合swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: ${springdoc.api-docs.path} #查看swagger文档

# 自定义高级客户端配置
hzy:
  elasticsearch:
    hostname: 127.0.0.1
    port: 9200